import "./globals.css";
import { Oxygen } from "next/font/google";
import { cn } from "@/lib/utils";
import { Header } from "@/components/layout/header";
import { AppCartProvider } from "@/components/shop/appCartProvider";
import { Toaster } from "@/components/ui/toaster"

const oxygen = Oxygen({ subsets: ["latin"], weight: ["300", "400", "700"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={cn(oxygen.className, "min-h-screen flex flex-col")}>
        <AppCartProvider>
          <Header />
          <main className="flex-grow">{children}</main>
          <Toaster />
        </AppCartProvider>
      </body>
    </html>
  );
}
